### ISSUE TITLE
Leased DHCP attribute doesn't update as fast as unknown devices 

### ISSUE THREAD

**Issue by PlantsThatsWhatsUp** [elad-bar/ha-edgeos#115]
Using EdgeRouter-X.
Trying to create an automation that when an IP is leased on my network, it notifies me and tells me what device it is. To do that, I need the attribute of unknown devices to update - but it doesn't update for quite a long time. Any clue why? The number changes quickly, but the list doesn't.

This is my automation - want to try this, but seems like a good chance I'll need a helper to store the old list and compare (for people looking to do the same):

````
alias: Notify on Device Connect/Disconnect
description: ""
trigger: 
  - platform: state
    entity_id: sensor.ubnt_unknown_devices
    attribute: leased
action:
  - service: homeassistant.update_entity
    entity_id: sensor.ubnt_unknown_devices
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - variables:
      new_list: "{{ trigger.to_state.attributes.leased | default([]) }}"
      old_list: "{{ trigger.from_state.attributes.leased | default([]) }}"
      connected: "{{ new_list | select('in', old_list) | list }}"
      disconnected: "{{ old_list | select('notin', new_list) | list }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ connected | count > 0 }}"
        sequence:
          - service: notify.mobile_app_galaxy_watch5_24be
            data:
              title: Device Connected
              message: "New device(s) connected: {{ connected | join(', ') }}"
      - conditions:
          - condition: template
            value_template: "{{ disconnected | count > 0 }}"
        sequence:
          - service: notify.mobile_app_sm_g990u2)
            data:
              title: Device Disconnected
              message: "Device(s) disconnected: {{ disconnected | join(', ') }}

**Comment by illuzn** [comment]
See my PR #119 and [my new blueprint](https://github.com/illuzn/homeassistant-edgeos-notification).

The idea was all yours but I made it a piece of cake to implement. It currently only notifies on all connects/ disconnects anyway but long term it is intended that the MAC address filters will be able to filter out known devices.

**Comment by PlantsThatsWhatsUp** [comment]
Looks promising! I'll try it out once the PR is accepted. Thanks!

**Comment by elad-bar** [comment]
released [v2.1.0](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.0), pls check and report

**Comment by elad-bar** [comment]
my automation:
```yaml
alias: Unknown Devices
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.ubnt_unknown_devices
condition:
  - condition: template
    alias: Check state changed
    value_template: "{{trigger.from_state.state != trigger.to_state.state}}"
action:
  - variables:
      state: "{{trigger.to_state.state | int}}"
      message: "{{trigger.to_state.attributes | join('\r\n') }}"
  - if:
      - condition: template
        value_template: "{{state > 0}}"
    then:
      - service: notify.mobile_app_samsung_s24_ultra
        data:
          title: "{{state}} unknown devices"
          message: "{{message}}"
          data:
            tag: Unknown Devices
            group: Unknown Devices
            color: red
mode: single

```
